---
title: "Zpětná vazba Discover"
---

```{r knitr_init, echo=FALSE, cache=FALSE, warning=F}
library(knitr)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

<i class="fa fa-camera-retro"> `r 12` </i> 

# Týmové workshopy

## Srovnání

```{r}
library(dplyr)
library(tidyr)

source("./lime-export/int/survey_215512_R_syntax_file.R")
data_int <- data
data_int <- data %>% select(-contains("groupTime"), -ends_with("Time"))
rm(data)
data_int$session <- "Int"
source("./lime-export/jul/survey_957564_R_syntax_file.R")
data_jul <- data
data_jul <- data %>% select(-contains("groupTime"), -contains("Time.."))
rm(data)
data_jul$session <- "Júl"
# source("./lime-export/jul/survey_XXXXXX_R_syntax_file.R")
# data_aug <- data
# rm(data)
# data_aug <- data %>% select(-contains("groupTime"), -contains("Time.."))
# data_aug$session <- "Aug"

# data <- bind_rows(data_jul, data_int, data_aug)
data <- bind_rows(data_jul, data_int)
```

## International

```{r Teamws}

library(forcats)

likertcz <- c("Určitě ano","Spíše ano","Nevím","Spíše ne","Určitě ne")
teamws <- data %>% select(contains("wsTymove"), session) %>%
  select(contains("_"), session) %>% 
  gather(key=workshop, value=value, -session) %>% 
  separate(workshop, into = c("variable","day")) %>% 
  group_by(session, day, variable) %>% 
  mutate(pocet=n()) %>% 
  group_by(session, day, variable, value) %>% 
  summarise(share=n()/mean(pocet)) %>%
  ungroup() %>% 
  mutate(value = fct_relevel(value, c(likertcz)),
         day   = fct_relevel(day, rev(c("po","st","pa","so"))),
         day   = fct_recode(day, c(Pondělí="po",Středa="st",Pátek="pa",Sobota="so")))

```

```{r}

library(ggiraph)
library(stringr)

teamws2 <- teamws %>% filter(session == "Int") %>% arrange(value) %>%
  filter(day!="Sobota") %>%
  mutate(tooltip = paste0(value, " ", format(share*100,digits = 1), "%"),
         tooltip = str_replace_all(tooltip,"'","&#8217")) %>% 
  ungroup() %>% mutate(dataid = as.character(row_number()))

tooltip_css <- "font-family:sans-serif; background-color:black; color: white; font-size: 8pt; padding:5px;border-radius:5px 5px 5px 5px;"

wsintplot <- ggplot(teamws2,aes(x = day, y = share, fill = value)) +
  geom_bar_interactive(stat = "identity", position = "stack",
                       aes(tooltip=tooltip, data_id=dataid)) +
  facet_wrap(~variable) + coord_flip()
```

```{r}
ggiraph(print(wsintplot), tooltip_extra_css=tooltip_css, hover_css = "opacity: .5;")
```

## Chart

```{r}
library(RColorBrewer)
library(ggplot2)
teamws %>% filter(session == "Júl") %>%  arrange(value) %>%
ggplot(aes(x = day, y = share, fill = value, order = value)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~variable) + coord_flip() +
  scale_fill_manual(values = rev(brewer.pal(5,"RdYlGn")))

```

# Two-part workshops

```{r}
ws2part <- data %>% filter(session=="Int") %>% select(contains("twopart")) %>% 
  group_by(twopartWhich) %>% summarise(mean=mean(twopartHowUseful, na.rm=T), count=n())
```

```{r, results="asis"}
htmltools::tag("i",varArgs = list("class"="fa fa-camera-retro","Hi"))
```

