---
title: "Leisure etc."
output: html_document
---

```{r knitr_init, echo=FALSE, cache=FALSE, warning=F}
library(knitr)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r include=F}
source("library.R")
source("loadprocesseddata.r")
```


# Should we change the programme?

## July

```{r, results="asis"}
print_bullets(ddf$volnycascozmenit[ddf$session=="Júl"])
```

## August

```{r, results="asis"}
print_bullets(ddf$volnycascozmenit[ddf$session=="Aug"])
```

## International

```{r, results="asis"}
print_bullets(ddf$volnycascozmenit[ddf$session=="Int"])
```

# Accommodation, food &c.

## July

```{r, results="asis"}
print_bullets(ddf$jidloatd[ddf$session=="Júl"])
```

## August

```{r, results="asis"}
print_bullets(ddf$jidloatd[ddf$session=="Aug"])
```

## International

```{r, results="asis"}
print_bullets(ddf$jidloatd[ddf$session=="Int"])
```